### ISSUE TITLE
Time offset

### ISSUE THREAD

**Issue by Nostrovx** [mihael-dev/High-Density-LineChart#1]
Hi,

I'm using High Density Line Chart in Qlik and everything has been working fine until I noticed today that there is a -1 hour offset in the time axis:

![image](https://user-images.githubusercontent.com/39997130/128165888-22f88e04-9ea7-4268-8d7c-a3c807c941fb.png)
![image](https://user-images.githubusercontent.com/39997130/128165920-bc0b4f71-d79e-48d9-a946-d75e03c1172d.png)

I tried with different data source and get the same result.

I had the problem with the mars version. I updated to the latest version today with no change.

Is there a work around? a fix?

Thx for the help.

=================================
=================================
It seems to have something to do with daylight saving as I notice on a wider data set that the offset comes exactly during the daylight saving period. No offset during summer time.

But that doesn't explain my example in the screen captures above.

**Comment by mihael-dev** [comment]
Fixed. Had some problems time zone and the transformation of a Qlik date to a JS date

**Comment by mihael-dev** [comment]
fixed
