### ISSUE TITLE
Time offset 2

### ISSUE THREAD

**Issue by Nostrovx** [mihael-dev/High-Density-LineChart#2]
Thx for this quick fix with plotly-2.2.0.

Unfortunately it seems that you forgot to update plotly in the lib folder.
I updated it manually and it works for winter time:
![image](https://user-images.githubusercontent.com/39997130/128674311-8911764b-00db-4054-b5d7-053d3136c9c0.png)

**But I now have a 2 hours offset in summer time.**

plotly-2.0.0:
winter: -1 hour offset
summer: 0 offset
![image](https://user-images.githubusercontent.com/39997130/128674021-7a57fae5-f0a3-425b-858a-881ef6350725.png)

plotly-2.2.0:
winter: 0 offset
summer: +2 hours offset
![image](https://user-images.githubusercontent.com/39997130/128674044-3ce3f71c-049d-46f6-b439-6d71b0e2a3aa.png)

**Comment by mihael-dev** [comment]
Hi. I have fixed the bug in the conversion of a Qlik data to a Javascript date in my code. This should work now ;-)

**Comment by Nostrovx** [comment]
Perfect, thx a lot!
