### ISSUE TITLE
Mouse over chart wrong legend

### ISSUE THREAD

**Issue by Nostrovx** [mihael-dev/High-Density-LineChart#3]
![image](https://user-images.githubusercontent.com/39997130/142209564-201e666d-0c07-4bc9-878c-b2ae9c46f131.png)

Hi, I would like to report a small issue with the mouse over data.
It seems to stick with the label for the first measure although the legend bellow the chart shows the right labels.

Here the purple line should be max(value).

**Comment by mihael-dev** [comment]
Thanks for reporting this issue. It should be fixed now.

**Comment by Nostrovx** [comment]
Excellent, thx!
